package uk.co.matbooth.jflatpak.manifest;

import java.util.HashMap;

/**
 * A hash map implementation to override the unnecessarily convoluted type
 * generated by JAXB.
 */
@SuppressWarnings("serial")
public class Environment extends HashMap<String, String> {

}
